### ISSUE TITLE
List of packages that adopted duecredit

### ISSUE THREAD

**Issue by fedorov** [duecredit/duecredit#110]
I just came across this repository by accident while reading [this article](https://peerj.com/articles/cs-86/). Very neat idea! Do you have any idea about how many python packages are using duecredit? Did you consider adding a list of such packages (or perhaps representative packages, if the list is too big) to create the sense of understanding of its adoption in the community?

An easy way to do this could be to add another entry to the repository, where package developers could self-add to mention their work and a URL.

**Comment by yarikoptic** [comment]
since we do not have any 'call home' "trojan/feature",  we have no ultimate list of packages (yet).  But according to https://github.com/search?q=duecredit&type=Code&utf8=%E2%9C%93  the number might slowly be growing!  we ourselves annotated our PyMVPA and later should integrate it with DataLad project, and also added injections of various degrees of detail for projects of others (https://github.com/duecredit/duecredit/tree/master/duecredit/injections) where authors either weren't yet ready to "buy in" or expressed their dislike of the idea ;)

> An easy way to do this could be to add another entry to the repository, where package developers could self-add to mention their work and a URL.
Could you elaborate how/where to add?  I guess ideally eventually we should provide some kind of central collection service with voluntary submissions.  That could provide the ultimate overview.

**Comment by fedorov** [comment]
> Could you elaborate how/where to add? I guess ideally eventually we should provide some kind of central collection service with voluntary submissions. That could provide the ultimate overview.

I didn't mean anything fancy or "ultimate". Just a prominent "Projects that adopted duecredit" section of README or a linked document with the list of hyperlinked projects that use duecredit, and a statement in the README that any project using duecredit is welcome (but not required) to add an entry to the "adopters" section by means of a pull request. I think adopters should be happy to do it, and it would also increase their visibility a little bit. For future adopters of duecredit, this will help understand the momentum behind it. I am sure there must be a few projects that you know of to create the initial list of adopters. Does this make sense?

**Comment by mvdoc** [comment]
Thanks for the idea @fedorov! I started adding a list on the README here #111
